services:
  - docker

stages:
  - build-latest
  - build-tag

jobs:
  include:
    - stage: push-latest
      install: skip
      script:
      - docker build -t dantebarba/cotizacion-mep-api:latest .

    - stage: push-tag
      if: tag IS present
      script:
      - docker build -t dantebarba/cotizacion-mep-api:$TRAVIS_TAG .
