services:
  - docker
  
script:
- docker build -t dantebarba/cotizacion-mep-api:latest .
- docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
- docker push dantebarba/cotizacion-mep-api:latest
